// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// @inject_tag: sql:",notnull,default:false"
	Completed bool `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	// @inject_tag: sql:",notnull,default:false"
	Deleted bool `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: sql:"type:timestamptz"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Todo) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Todo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Todo) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type TodoRequestCreateInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoRequestCreateInfo) Reset()         { *m = TodoRequestCreateInfo{} }
func (m *TodoRequestCreateInfo) String() string { return proto.CompactTextString(m) }
func (*TodoRequestCreateInfo) ProtoMessage()    {}
func (*TodoRequestCreateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodoRequestCreateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoRequestCreateInfo.Unmarshal(m, b)
}
func (m *TodoRequestCreateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoRequestCreateInfo.Marshal(b, m, deterministic)
}
func (m *TodoRequestCreateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoRequestCreateInfo.Merge(m, src)
}
func (m *TodoRequestCreateInfo) XXX_Size() int {
	return xxx_messageInfo_TodoRequestCreateInfo.Size(m)
}
func (m *TodoRequestCreateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoRequestCreateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TodoRequestCreateInfo proto.InternalMessageInfo

func (m *TodoRequestCreateInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TodoRequestCreateInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateTodoRequest struct {
	Item                 *TodoRequestCreateInfo `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (m *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(m, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetItem() *TodoRequestCreateInfo {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateTodoResponse struct {
	ResponseStatus       *ResponseStatus `protobuf:"bytes,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateTodoResponse) Reset()         { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()    {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *CreateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoResponse.Unmarshal(m, b)
}
func (m *CreateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoResponse.Marshal(b, m, deterministic)
}
func (m *CreateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoResponse.Merge(m, src)
}
func (m *CreateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTodoResponse.Size(m)
}
func (m *CreateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoResponse proto.InternalMessageInfo

func (m *CreateTodoResponse) GetResponseStatus() *ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func (m *CreateTodoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoRequest) Reset()         { *m = GetTodoRequest{} }
func (m *GetTodoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodoRequest) ProtoMessage()    {}
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *GetTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoRequest.Unmarshal(m, b)
}
func (m *GetTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoRequest.Marshal(b, m, deterministic)
}
func (m *GetTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoRequest.Merge(m, src)
}
func (m *GetTodoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodoRequest.Size(m)
}
func (m *GetTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoRequest proto.InternalMessageInfo

func (m *GetTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodoResponse struct {
	ResponseStatus       *ResponseStatus `protobuf:"bytes,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	Item                 *Todo           `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTodoResponse) Reset()         { *m = GetTodoResponse{} }
func (m *GetTodoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodoResponse) ProtoMessage()    {}
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *GetTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoResponse.Unmarshal(m, b)
}
func (m *GetTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoResponse.Marshal(b, m, deterministic)
}
func (m *GetTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoResponse.Merge(m, src)
}
func (m *GetTodoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodoResponse.Size(m)
}
func (m *GetTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoResponse proto.InternalMessageInfo

func (m *GetTodoResponse) GetResponseStatus() *ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func (m *GetTodoResponse) GetItem() *Todo {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListTodoRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Marker               string   `protobuf:"bytes,2,opt,name=marker,proto3" json:"marker,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoRequest) Reset()         { *m = ListTodoRequest{} }
func (m *ListTodoRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodoRequest) ProtoMessage()    {}
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *ListTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoRequest.Unmarshal(m, b)
}
func (m *ListTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoRequest.Marshal(b, m, deterministic)
}
func (m *ListTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoRequest.Merge(m, src)
}
func (m *ListTodoRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodoRequest.Size(m)
}
func (m *ListTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoRequest proto.InternalMessageInfo

func (m *ListTodoRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListTodoRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ListTodoRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type ListTodoResponse struct {
	ResponseStatus       *ResponseStatus `protobuf:"bytes,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	Items                []*Todo         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListTodoResponse) Reset()         { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()    {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *ListTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoResponse.Unmarshal(m, b)
}
func (m *ListTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoResponse.Marshal(b, m, deterministic)
}
func (m *ListTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoResponse.Merge(m, src)
}
func (m *ListTodoResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoResponse.Size(m)
}
func (m *ListTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoResponse proto.InternalMessageInfo

func (m *ListTodoResponse) GetResponseStatus() *ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func (m *ListTodoResponse) GetItems() []*Todo {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{8}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTodoResponse struct {
	ResponseStatus       *ResponseStatus `protobuf:"bytes,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeleteTodoResponse) Reset()         { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()    {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{9}
}

func (m *DeleteTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoResponse.Unmarshal(m, b)
}
func (m *DeleteTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoResponse.Merge(m, src)
}
func (m *DeleteTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoResponse.Size(m)
}
func (m *DeleteTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoResponse proto.InternalMessageInfo

func (m *DeleteTodoResponse) GetResponseStatus() *ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

type TodoRequestUpdateInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoRequestUpdateInfo) Reset()         { *m = TodoRequestUpdateInfo{} }
func (m *TodoRequestUpdateInfo) String() string { return proto.CompactTextString(m) }
func (*TodoRequestUpdateInfo) ProtoMessage()    {}
func (*TodoRequestUpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{10}
}

func (m *TodoRequestUpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoRequestUpdateInfo.Unmarshal(m, b)
}
func (m *TodoRequestUpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoRequestUpdateInfo.Marshal(b, m, deterministic)
}
func (m *TodoRequestUpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoRequestUpdateInfo.Merge(m, src)
}
func (m *TodoRequestUpdateInfo) XXX_Size() int {
	return xxx_messageInfo_TodoRequestUpdateInfo.Size(m)
}
func (m *TodoRequestUpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoRequestUpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TodoRequestUpdateInfo proto.InternalMessageInfo

func (m *TodoRequestUpdateInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TodoRequestUpdateInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TodoRequestUpdateInfo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type UpdateTodoRequest struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item                 *TodoRequestUpdateInfo `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateTodoRequest) Reset()         { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()    {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{11}
}

func (m *UpdateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoRequest.Unmarshal(m, b)
}
func (m *UpdateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoRequest.Merge(m, src)
}
func (m *UpdateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoRequest.Size(m)
}
func (m *UpdateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoRequest proto.InternalMessageInfo

func (m *UpdateTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTodoRequest) GetItem() *TodoRequestUpdateInfo {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateTodoReponse struct {
	ResponseStatus       *ResponseStatus `protobuf:"bytes,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateTodoReponse) Reset()         { *m = UpdateTodoReponse{} }
func (m *UpdateTodoReponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoReponse) ProtoMessage()    {}
func (*UpdateTodoReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{12}
}

func (m *UpdateTodoReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoReponse.Unmarshal(m, b)
}
func (m *UpdateTodoReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoReponse.Marshal(b, m, deterministic)
}
func (m *UpdateTodoReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoReponse.Merge(m, src)
}
func (m *UpdateTodoReponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoReponse.Size(m)
}
func (m *UpdateTodoReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoReponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoReponse proto.InternalMessageInfo

func (m *UpdateTodoReponse) GetResponseStatus() *ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

type ResponseStatus struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{13}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Todo)(nil), "todo.v1.Todo")
	proto.RegisterType((*TodoRequestCreateInfo)(nil), "todo.v1.TodoRequestCreateInfo")
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.v1.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "todo.v1.CreateTodoResponse")
	proto.RegisterType((*GetTodoRequest)(nil), "todo.v1.GetTodoRequest")
	proto.RegisterType((*GetTodoResponse)(nil), "todo.v1.GetTodoResponse")
	proto.RegisterType((*ListTodoRequest)(nil), "todo.v1.ListTodoRequest")
	proto.RegisterType((*ListTodoResponse)(nil), "todo.v1.ListTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "todo.v1.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "todo.v1.DeleteTodoResponse")
	proto.RegisterType((*TodoRequestUpdateInfo)(nil), "todo.v1.TodoRequestUpdateInfo")
	proto.RegisterType((*UpdateTodoRequest)(nil), "todo.v1.UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoReponse)(nil), "todo.v1.UpdateTodoReponse")
	proto.RegisterType((*ResponseStatus)(nil), "todo.v1.ResponseStatus")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x9c, 0xa4, 0x49, 0x27, 0x6a, 0x7e, 0x46, 0xa4, 0x18, 0xb7, 0x82, 0xe0, 0x5e, 0x10,
	0x07, 0x5b, 0x0d, 0x27, 0x38, 0x80, 0x0a, 0x48, 0x15, 0x12, 0x12, 0xc2, 0x49, 0x85, 0x04, 0xaa,
	0x90, 0x1b, 0x6f, 0xa3, 0x15, 0x71, 0x6c, 0xec, 0x4d, 0x84, 0x84, 0xb8, 0xf0, 0x0a, 0x3c, 0x1a,
	0x3c, 0x02, 0x8f, 0xc1, 0x81, 0xf5, 0xee, 0x3a, 0xb6, 0xe3, 0x90, 0x1e, 0xc8, 0x6d, 0xc7, 0xdf,
	0xec, 0x37, 0xdf, 0xfc, 0xad, 0x01, 0x58, 0xe0, 0x05, 0x56, 0x18, 0x05, 0x2c, 0xc0, 0x86, 0x38,
	0x2f, 0x4f, 0x8d, 0xe3, 0x69, 0x10, 0x4c, 0x67, 0xc4, 0x76, 0x43, 0x6a, 0xbb, 0xf3, 0x79, 0xc0,
	0x5c, 0x46, 0x83, 0x79, 0x2c, 0xdd, 0x8c, 0x7b, 0x0a, 0x15, 0xd6, 0xd5, 0xe2, 0xda, 0x66, 0xd4,
	0x27, 0x31, 0x73, 0xfd, 0x50, 0x3a, 0x98, 0x7f, 0x2a, 0x50, 0x1b, 0x73, 0x2a, 0x6c, 0x83, 0x46,
	0x3d, 0xbd, 0x32, 0xa8, 0x3c, 0xd8, 0x77, 0xf8, 0x09, 0x6f, 0x41, 0x9d, 0x51, 0x36, 0x23, 0xba,
	0x26, 0x3e, 0x49, 0x03, 0x07, 0xd0, 0xf2, 0x48, 0x3c, 0x89, 0x68, 0x98, 0x44, 0xd1, 0xab, 0x02,
	0xcb, 0x7f, 0xc2, 0x63, 0xd8, 0x9f, 0x04, 0x7e, 0x38, 0x23, 0x8c, 0x78, 0x7a, 0x8d, 0xe3, 0x4d,
	0x27, 0xfb, 0x80, 0x3a, 0x34, 0x3c, 0x22, 0xb1, 0xba, 0xc0, 0x52, 0x13, 0x1f, 0x03, 0x4c, 0x22,
	0xe2, 0xf2, 0xe3, 0x47, 0x97, 0xe9, 0x7b, 0x1c, 0x6c, 0x0d, 0x0d, 0x4b, 0xca, 0xb7, 0x52, 0xf9,
	0xd6, 0x38, 0x95, 0xcf, 0x49, 0xa5, 0xf7, 0x19, 0x4b, 0xae, 0x2e, 0x42, 0x2f, 0xbd, 0xda, 0xb8,
	0xf9, 0xaa, 0xf2, 0x3e, 0x63, 0xe6, 0x1b, 0xe8, 0x27, 0xd9, 0x3b, 0xe4, 0xf3, 0x82, 0x83, 0x2f,
	0x04, 0xe5, 0xab, 0xf9, 0x75, 0x90, 0xa5, 0x5f, 0xd9, 0x92, 0xbe, 0x56, 0x4a, 0xdf, 0x3c, 0x87,
	0x9e, 0x64, 0xc9, 0xd1, 0xe2, 0x10, 0x6a, 0x94, 0x11, 0x5f, 0x70, 0xb5, 0x86, 0x77, 0x2d, 0xd5,
	0x3b, 0x6b, 0x63, 0x68, 0x47, 0xf8, 0x9a, 0x04, 0x30, 0x4f, 0x14, 0x87, 0xbc, 0xa9, 0x04, 0x9f,
	0x41, 0x3b, 0x52, 0xe7, 0x11, 0xef, 0xf4, 0x22, 0x56, 0x9c, 0xb7, 0x57, 0x9c, 0x4e, 0x01, 0x76,
	0xd6, 0xdc, 0x55, 0x9b, 0xb5, 0xb4, 0xcd, 0xe6, 0x00, 0xda, 0xe7, 0x84, 0xe5, 0xc5, 0xae, 0x0d,
	0x82, 0xb9, 0x80, 0xce, 0xca, 0x63, 0x57, 0x2a, 0xee, 0xab, 0x82, 0x68, 0xe2, 0xda, 0x41, 0xb1,
	0x20, 0x32, 0xff, 0x4b, 0xe8, 0xbc, 0xa6, 0x71, 0x41, 0x19, 0xef, 0xc9, 0x8c, 0xfa, 0x94, 0x89,
	0x68, 0x75, 0x47, 0x1a, 0x78, 0x08, 0x7b, 0xbe, 0x1b, 0x7d, 0x22, 0x91, 0xca, 0x4a, 0x59, 0xc5,
	0x41, 0xac, 0xae, 0x0d, 0xa2, 0xf9, 0x05, 0xba, 0x19, 0xfd, 0xae, 0xd2, 0x3a, 0x81, 0x7a, 0xa2,
	0x3d, 0xe6, 0x4a, 0xaa, 0xe5, 0xbc, 0x24, 0x66, 0x9e, 0x40, 0xef, 0xa5, 0x98, 0xf9, 0x6d, 0x45,
	0xbf, 0x00, 0xcc, 0x3b, 0xed, 0x48, 0xa0, 0xe9, 0x17, 0xc6, 0xfd, 0x42, 0xac, 0xc1, 0xff, 0x8c,
	0xfb, 0x0d, 0x45, 0x7e, 0x07, 0x3d, 0x19, 0x63, 0x4b, 0xaa, 0xab, 0xe5, 0xd0, 0xfe, 0xbd, 0x1c,
	0x99, 0x50, 0x35, 0x1c, 0xe3, 0x22, 0xf1, 0x8e, 0xaa, 0xf3, 0x14, 0xda, 0x45, 0x0f, 0x44, 0xa8,
	0x4d, 0x02, 0x8f, 0xa8, 0x81, 0x13, 0xe7, 0xe4, 0x09, 0xe3, 0x0f, 0x49, 0xec, 0x4e, 0xd3, 0xa7,
	0x31, 0x35, 0x87, 0xbf, 0xaa, 0xd0, 0x4a, 0x04, 0x8d, 0x48, 0xb4, 0xa4, 0x13, 0x82, 0x97, 0x00,
	0xd9, 0x0a, 0xa3, 0xb1, 0x92, 0x51, 0x7a, 0x20, 0x8c, 0xa3, 0x8d, 0x98, 0x94, 0x62, 0x1e, 0x7e,
	0xff, 0xf9, 0xfb, 0x87, 0xd6, 0x35, 0x9b, 0xf6, 0xf2, 0xd4, 0x4e, 0xfc, 0x9e, 0x88, 0x22, 0xe0,
	0x08, 0x1a, 0x6a, 0x31, 0x31, 0x4b, 0xb1, 0xb8, 0xcc, 0x86, 0x5e, 0x06, 0x14, 0x6b, 0x5f, 0xb0,
	0x76, 0xf0, 0x20, 0x65, 0xb5, 0xbf, 0x52, 0xef, 0x1b, 0xbe, 0x85, 0x66, 0xba, 0x17, 0x98, 0x5d,
	0x5e, 0xdb, 0x44, 0xe3, 0xce, 0x06, 0x44, 0xf1, 0x76, 0x05, 0x2f, 0xe0, 0x4a, 0x2d, 0xba, 0x00,
	0x59, 0xb3, 0x72, 0x65, 0x28, 0x8d, 0x86, 0xb1, 0x19, 0x93, 0xbc, 0x47, 0x82, 0xb7, 0x6f, 0x14,
	0xf5, 0xaa, 0x52, 0x7c, 0x00, 0xc8, 0xd6, 0x25, 0x17, 0xa2, 0xb4, 0x68, 0x5b, 0x43, 0xa8, 0x92,
	0x3c, 0x2c, 0x86, 0x78, 0x0e, 0xef, 0x9b, 0xe9, 0x4f, 0xe4, 0x6a, 0x4f, 0x9c, 0x1e, 0xfd, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xe3, 0x8b, 0x03, 0x14, 0x8b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error)
	ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error)
	UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoReponse, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*UpdateTodoReponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := c.cc.Invoke(ctx, "/todo.v1.TodoService/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error) {
	out := new(GetTodoResponse)
	err := c.cc.Invoke(ctx, "/todo.v1.TodoService/GetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	err := c.cc.Invoke(ctx, "/todo.v1.TodoService/ListTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoReponse, error) {
	out := new(UpdateTodoReponse)
	err := c.cc.Invoke(ctx, "/todo.v1.TodoService/UpdateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*UpdateTodoReponse, error) {
	out := new(UpdateTodoReponse)
	err := c.cc.Invoke(ctx, "/todo.v1.TodoService/DeleteTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
	GetTodo(context.Context, *GetTodoRequest) (*GetTodoResponse, error)
	ListTodo(context.Context, *ListTodoRequest) (*ListTodoResponse, error)
	UpdateTodo(context.Context, *UpdateTodoRequest) (*UpdateTodoReponse, error)
	DeleteTodo(context.Context, *DeleteTodoRequest) (*UpdateTodoReponse, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) CreateTodo(ctx context.Context, req *CreateTodoRequest) (*CreateTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (*UnimplementedTodoServiceServer) GetTodo(ctx context.Context, req *GetTodoRequest) (*GetTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodo not implemented")
}
func (*UnimplementedTodoServiceServer) ListTodo(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTodo not implemented")
}
func (*UnimplementedTodoServiceServer) UpdateTodo(ctx context.Context, req *UpdateTodoRequest) (*UpdateTodoReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTodo not implemented")
}
func (*UnimplementedTodoServiceServer) DeleteTodo(ctx context.Context, req *DeleteTodoRequest) (*UpdateTodoReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTodo not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*GetTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/ListTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodo(ctx, req.(*ListTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*UpdateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteTodo(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "GetTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
		{
			MethodName: "ListTodo",
			Handler:    _TodoService_ListTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _TodoService_DeleteTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
