// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package customerfeedback

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseInfo struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// base on http code
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInfo) Reset()         { *m = ResponseInfo{} }
func (m *ResponseInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseInfo) ProtoMessage()    {}
func (*ResponseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{0}
}
func (m *ResponseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInfo.Unmarshal(m, b)
}
func (m *ResponseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInfo.Marshal(b, m, deterministic)
}
func (dst *ResponseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInfo.Merge(dst, src)
}
func (m *ResponseInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseInfo.Size(m)
}
func (m *ResponseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInfo proto.InternalMessageInfo

func (m *ResponseInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseInfo) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type PagingRequest struct {
	PageNumber           int32    `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagingRequest) Reset()         { *m = PagingRequest{} }
func (m *PagingRequest) String() string { return proto.CompactTextString(m) }
func (*PagingRequest) ProtoMessage()    {}
func (*PagingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{1}
}
func (m *PagingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingRequest.Unmarshal(m, b)
}
func (m *PagingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingRequest.Marshal(b, m, deterministic)
}
func (dst *PagingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingRequest.Merge(dst, src)
}
func (m *PagingRequest) XXX_Size() int {
	return xxx_messageInfo_PagingRequest.Size(m)
}
func (m *PagingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PagingRequest proto.InternalMessageInfo

func (m *PagingRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PagingRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type PagingResponse struct {
	TotalPage            int32    `protobuf:"varint,1,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	TotalRecord          int32    `protobuf:"varint,2,opt,name=totalRecord,proto3" json:"totalRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagingResponse) Reset()         { *m = PagingResponse{} }
func (m *PagingResponse) String() string { return proto.CompactTextString(m) }
func (*PagingResponse) ProtoMessage()    {}
func (*PagingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{2}
}
func (m *PagingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingResponse.Unmarshal(m, b)
}
func (m *PagingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingResponse.Marshal(b, m, deterministic)
}
func (dst *PagingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingResponse.Merge(dst, src)
}
func (m *PagingResponse) XXX_Size() int {
	return xxx_messageInfo_PagingResponse.Size(m)
}
func (m *PagingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PagingResponse proto.InternalMessageInfo

func (m *PagingResponse) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *PagingResponse) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

// passenger
type CreatePassengerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePassengerRequest) Reset()         { *m = CreatePassengerRequest{} }
func (m *CreatePassengerRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePassengerRequest) ProtoMessage()    {}
func (*CreatePassengerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{3}
}
func (m *CreatePassengerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePassengerRequest.Unmarshal(m, b)
}
func (m *CreatePassengerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePassengerRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePassengerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePassengerRequest.Merge(dst, src)
}
func (m *CreatePassengerRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePassengerRequest.Size(m)
}
func (m *CreatePassengerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePassengerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePassengerRequest proto.InternalMessageInfo

func (m *CreatePassengerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PassengerInfoResponse struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResponseStatus       *ResponseInfo `protobuf:"bytes,3,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PassengerInfoResponse) Reset()         { *m = PassengerInfoResponse{} }
func (m *PassengerInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PassengerInfoResponse) ProtoMessage()    {}
func (*PassengerInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{4}
}
func (m *PassengerInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerInfoResponse.Unmarshal(m, b)
}
func (m *PassengerInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerInfoResponse.Marshal(b, m, deterministic)
}
func (dst *PassengerInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerInfoResponse.Merge(dst, src)
}
func (m *PassengerInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PassengerInfoResponse.Size(m)
}
func (m *PassengerInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerInfoResponse proto.InternalMessageInfo

func (m *PassengerInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PassengerInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PassengerInfoResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

type GetPassengerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPassengerRequest) Reset()         { *m = GetPassengerRequest{} }
func (m *GetPassengerRequest) String() string { return proto.CompactTextString(m) }
func (*GetPassengerRequest) ProtoMessage()    {}
func (*GetPassengerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{5}
}
func (m *GetPassengerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerRequest.Unmarshal(m, b)
}
func (m *GetPassengerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerRequest.Marshal(b, m, deterministic)
}
func (dst *GetPassengerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerRequest.Merge(dst, src)
}
func (m *GetPassengerRequest) XXX_Size() int {
	return xxx_messageInfo_GetPassengerRequest.Size(m)
}
func (m *GetPassengerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerRequest proto.InternalMessageInfo

func (m *GetPassengerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// booking
type Location struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{6}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type CreateBookingRequest struct {
	PassengerId          string    `protobuf:"bytes,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	From                 *Location `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Location `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateBookingRequest) Reset()         { *m = CreateBookingRequest{} }
func (m *CreateBookingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookingRequest) ProtoMessage()    {}
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{7}
}
func (m *CreateBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingRequest.Unmarshal(m, b)
}
func (m *CreateBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingRequest.Merge(dst, src)
}
func (m *CreateBookingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookingRequest.Size(m)
}
func (m *CreateBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingRequest proto.InternalMessageInfo

func (m *CreateBookingRequest) GetPassengerId() string {
	if m != nil {
		return m.PassengerId
	}
	return ""
}

func (m *CreateBookingRequest) GetFrom() *Location {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *CreateBookingRequest) GetTo() *Location {
	if m != nil {
		return m.To
	}
	return nil
}

type BookingInfoResponse struct {
	BookingCode          string               `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	From                 *Location            `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Location            `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	IsFinish             bool                 `protobuf:"varint,4,opt,name=isFinish,proto3" json:"isFinish,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	FinishAt             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=finishAt,proto3" json:"finishAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BookingInfoResponse) Reset()         { *m = BookingInfoResponse{} }
func (m *BookingInfoResponse) String() string { return proto.CompactTextString(m) }
func (*BookingInfoResponse) ProtoMessage()    {}
func (*BookingInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{8}
}
func (m *BookingInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingInfoResponse.Unmarshal(m, b)
}
func (m *BookingInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingInfoResponse.Marshal(b, m, deterministic)
}
func (dst *BookingInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingInfoResponse.Merge(dst, src)
}
func (m *BookingInfoResponse) XXX_Size() int {
	return xxx_messageInfo_BookingInfoResponse.Size(m)
}
func (m *BookingInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingInfoResponse proto.InternalMessageInfo

func (m *BookingInfoResponse) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *BookingInfoResponse) GetFrom() *Location {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *BookingInfoResponse) GetTo() *Location {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *BookingInfoResponse) GetIsFinish() bool {
	if m != nil {
		return m.IsFinish
	}
	return false
}

func (m *BookingInfoResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *BookingInfoResponse) GetFinishAt() *timestamp.Timestamp {
	if m != nil {
		return m.FinishAt
	}
	return nil
}

type CreateBookingResponse struct {
	Booking              *BookingInfoResponse `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	ResponseStatus       *ResponseInfo        `protobuf:"bytes,2,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateBookingResponse) Reset()         { *m = CreateBookingResponse{} }
func (m *CreateBookingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookingResponse) ProtoMessage()    {}
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{9}
}
func (m *CreateBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingResponse.Unmarshal(m, b)
}
func (m *CreateBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingResponse.Marshal(b, m, deterministic)
}
func (dst *CreateBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingResponse.Merge(dst, src)
}
func (m *CreateBookingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookingResponse.Size(m)
}
func (m *CreateBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingResponse proto.InternalMessageInfo

func (m *CreateBookingResponse) GetBooking() *BookingInfoResponse {
	if m != nil {
		return m.Booking
	}
	return nil
}

func (m *CreateBookingResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

type GetBookingRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingRequest) Reset()         { *m = GetBookingRequest{} }
func (m *GetBookingRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookingRequest) ProtoMessage()    {}
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{10}
}
func (m *GetBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingRequest.Unmarshal(m, b)
}
func (m *GetBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingRequest.Marshal(b, m, deterministic)
}
func (dst *GetBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingRequest.Merge(dst, src)
}
func (m *GetBookingRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookingRequest.Size(m)
}
func (m *GetBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingRequest proto.InternalMessageInfo

func (m *GetBookingRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type GetBookingRequestByPassengerId struct {
	PassengerId          string         `protobuf:"bytes,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	PagingRequest        *PagingRequest `protobuf:"bytes,2,opt,name=pagingRequest,proto3" json:"pagingRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBookingRequestByPassengerId) Reset()         { *m = GetBookingRequestByPassengerId{} }
func (m *GetBookingRequestByPassengerId) String() string { return proto.CompactTextString(m) }
func (*GetBookingRequestByPassengerId) ProtoMessage()    {}
func (*GetBookingRequestByPassengerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{11}
}
func (m *GetBookingRequestByPassengerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingRequestByPassengerId.Unmarshal(m, b)
}
func (m *GetBookingRequestByPassengerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingRequestByPassengerId.Marshal(b, m, deterministic)
}
func (dst *GetBookingRequestByPassengerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingRequestByPassengerId.Merge(dst, src)
}
func (m *GetBookingRequestByPassengerId) XXX_Size() int {
	return xxx_messageInfo_GetBookingRequestByPassengerId.Size(m)
}
func (m *GetBookingRequestByPassengerId) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingRequestByPassengerId.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingRequestByPassengerId proto.InternalMessageInfo

func (m *GetBookingRequestByPassengerId) GetPassengerId() string {
	if m != nil {
		return m.PassengerId
	}
	return ""
}

func (m *GetBookingRequestByPassengerId) GetPagingRequest() *PagingRequest {
	if m != nil {
		return m.PagingRequest
	}
	return nil
}

type PassengerBookingResponse struct {
	Bookings             []*BookingInfoResponse `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	ResponseStatus       *ResponseInfo          `protobuf:"bytes,2,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	PagingResponse       *PagingResponse        `protobuf:"bytes,5,opt,name=pagingResponse,proto3" json:"pagingResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PassengerBookingResponse) Reset()         { *m = PassengerBookingResponse{} }
func (m *PassengerBookingResponse) String() string { return proto.CompactTextString(m) }
func (*PassengerBookingResponse) ProtoMessage()    {}
func (*PassengerBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{12}
}
func (m *PassengerBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerBookingResponse.Unmarshal(m, b)
}
func (m *PassengerBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerBookingResponse.Marshal(b, m, deterministic)
}
func (dst *PassengerBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerBookingResponse.Merge(dst, src)
}
func (m *PassengerBookingResponse) XXX_Size() int {
	return xxx_messageInfo_PassengerBookingResponse.Size(m)
}
func (m *PassengerBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerBookingResponse proto.InternalMessageInfo

func (m *PassengerBookingResponse) GetBookings() []*BookingInfoResponse {
	if m != nil {
		return m.Bookings
	}
	return nil
}

func (m *PassengerBookingResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func (m *PassengerBookingResponse) GetPagingResponse() *PagingResponse {
	if m != nil {
		return m.PagingResponse
	}
	return nil
}

// feedback
type CreateFeedbackRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	FeedbackMessage      string   `protobuf:"bytes,2,opt,name=feedbackMessage,proto3" json:"feedbackMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFeedbackRequest) Reset()         { *m = CreateFeedbackRequest{} }
func (m *CreateFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFeedbackRequest) ProtoMessage()    {}
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{13}
}
func (m *CreateFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeedbackRequest.Unmarshal(m, b)
}
func (m *CreateFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeedbackRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeedbackRequest.Merge(dst, src)
}
func (m *CreateFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFeedbackRequest.Size(m)
}
func (m *CreateFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeedbackRequest proto.InternalMessageInfo

func (m *CreateFeedbackRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *CreateFeedbackRequest) GetFeedbackMessage() string {
	if m != nil {
		return m.FeedbackMessage
	}
	return ""
}

type CreateFeedbackResponse struct {
	ResponseStatus       *ResponseInfo `protobuf:"bytes,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateFeedbackResponse) Reset()         { *m = CreateFeedbackResponse{} }
func (m *CreateFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFeedbackResponse) ProtoMessage()    {}
func (*CreateFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{14}
}
func (m *CreateFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeedbackResponse.Unmarshal(m, b)
}
func (m *CreateFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeedbackResponse.Marshal(b, m, deterministic)
}
func (dst *CreateFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeedbackResponse.Merge(dst, src)
}
func (m *CreateFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFeedbackResponse.Size(m)
}
func (m *CreateFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeedbackResponse proto.InternalMessageInfo

func (m *CreateFeedbackResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

type FeedbackInfoResponse struct {
	BookingCode          string               `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	FeedbackMessage      string               `protobuf:"bytes,2,opt,name=feedbackMessage,proto3" json:"feedbackMessage,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedbackInfoResponse) Reset()         { *m = FeedbackInfoResponse{} }
func (m *FeedbackInfoResponse) String() string { return proto.CompactTextString(m) }
func (*FeedbackInfoResponse) ProtoMessage()    {}
func (*FeedbackInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{15}
}
func (m *FeedbackInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedbackInfoResponse.Unmarshal(m, b)
}
func (m *FeedbackInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedbackInfoResponse.Marshal(b, m, deterministic)
}
func (dst *FeedbackInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedbackInfoResponse.Merge(dst, src)
}
func (m *FeedbackInfoResponse) XXX_Size() int {
	return xxx_messageInfo_FeedbackInfoResponse.Size(m)
}
func (m *FeedbackInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedbackInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedbackInfoResponse proto.InternalMessageInfo

func (m *FeedbackInfoResponse) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *FeedbackInfoResponse) GetFeedbackMessage() string {
	if m != nil {
		return m.FeedbackMessage
	}
	return ""
}

func (m *FeedbackInfoResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type GetFeedbackResponse struct {
	FeedBack             *FeedbackInfoResponse `protobuf:"bytes,1,opt,name=feedBack,proto3" json:"feedBack,omitempty"`
	ResponseStatus       *ResponseInfo         `protobuf:"bytes,2,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetFeedbackResponse) Reset()         { *m = GetFeedbackResponse{} }
func (m *GetFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackResponse) ProtoMessage()    {}
func (*GetFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{16}
}
func (m *GetFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackResponse.Unmarshal(m, b)
}
func (m *GetFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackResponse.Marshal(b, m, deterministic)
}
func (dst *GetFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackResponse.Merge(dst, src)
}
func (m *GetFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackResponse.Size(m)
}
func (m *GetFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackResponse proto.InternalMessageInfo

func (m *GetFeedbackResponse) GetFeedBack() *FeedbackInfoResponse {
	if m != nil {
		return m.FeedBack
	}
	return nil
}

func (m *GetFeedbackResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

type GetFeedbackByBookingCode struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedbackByBookingCode) Reset()         { *m = GetFeedbackByBookingCode{} }
func (m *GetFeedbackByBookingCode) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByBookingCode) ProtoMessage()    {}
func (*GetFeedbackByBookingCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{17}
}
func (m *GetFeedbackByBookingCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByBookingCode.Unmarshal(m, b)
}
func (m *GetFeedbackByBookingCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByBookingCode.Marshal(b, m, deterministic)
}
func (dst *GetFeedbackByBookingCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByBookingCode.Merge(dst, src)
}
func (m *GetFeedbackByBookingCode) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByBookingCode.Size(m)
}
func (m *GetFeedbackByBookingCode) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByBookingCode.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByBookingCode proto.InternalMessageInfo

func (m *GetFeedbackByBookingCode) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type GetFeedbackByPassengerId struct {
	PassengerId          string         `protobuf:"bytes,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	PagingRequest        *PagingRequest `protobuf:"bytes,2,opt,name=pagingRequest,proto3" json:"pagingRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetFeedbackByPassengerId) Reset()         { *m = GetFeedbackByPassengerId{} }
func (m *GetFeedbackByPassengerId) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByPassengerId) ProtoMessage()    {}
func (*GetFeedbackByPassengerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{18}
}
func (m *GetFeedbackByPassengerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByPassengerId.Unmarshal(m, b)
}
func (m *GetFeedbackByPassengerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByPassengerId.Marshal(b, m, deterministic)
}
func (dst *GetFeedbackByPassengerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByPassengerId.Merge(dst, src)
}
func (m *GetFeedbackByPassengerId) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByPassengerId.Size(m)
}
func (m *GetFeedbackByPassengerId) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByPassengerId.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByPassengerId proto.InternalMessageInfo

func (m *GetFeedbackByPassengerId) GetPassengerId() string {
	if m != nil {
		return m.PassengerId
	}
	return ""
}

func (m *GetFeedbackByPassengerId) GetPagingRequest() *PagingRequest {
	if m != nil {
		return m.PagingRequest
	}
	return nil
}

type PassengerFeedbackResponse struct {
	Feedbacks            []*FeedbackInfoResponse `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	ResponseStatus       *ResponseInfo           `protobuf:"bytes,2,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	PagingResponse       *PagingResponse         `protobuf:"bytes,5,opt,name=pagingResponse,proto3" json:"pagingResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PassengerFeedbackResponse) Reset()         { *m = PassengerFeedbackResponse{} }
func (m *PassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedbackResponse) ProtoMessage()    {}
func (*PassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{19}
}
func (m *PassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *PassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (dst *PassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedbackResponse.Merge(dst, src)
}
func (m *PassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedbackResponse.Size(m)
}
func (m *PassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedbackResponse proto.InternalMessageInfo

func (m *PassengerFeedbackResponse) GetFeedbacks() []*FeedbackInfoResponse {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

func (m *PassengerFeedbackResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func (m *PassengerFeedbackResponse) GetPagingResponse() *PagingResponse {
	if m != nil {
		return m.PagingResponse
	}
	return nil
}

type DeleteFeedbackByPassengerId struct {
	PassengerId          string   `protobuf:"bytes,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeedbackByPassengerId) Reset()         { *m = DeleteFeedbackByPassengerId{} }
func (m *DeleteFeedbackByPassengerId) String() string { return proto.CompactTextString(m) }
func (*DeleteFeedbackByPassengerId) ProtoMessage()    {}
func (*DeleteFeedbackByPassengerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{20}
}
func (m *DeleteFeedbackByPassengerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeedbackByPassengerId.Unmarshal(m, b)
}
func (m *DeleteFeedbackByPassengerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeedbackByPassengerId.Marshal(b, m, deterministic)
}
func (dst *DeleteFeedbackByPassengerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeedbackByPassengerId.Merge(dst, src)
}
func (m *DeleteFeedbackByPassengerId) XXX_Size() int {
	return xxx_messageInfo_DeleteFeedbackByPassengerId.Size(m)
}
func (m *DeleteFeedbackByPassengerId) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeedbackByPassengerId.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeedbackByPassengerId proto.InternalMessageInfo

func (m *DeleteFeedbackByPassengerId) GetPassengerId() string {
	if m != nil {
		return m.PassengerId
	}
	return ""
}

type DeleteFeedBackResponse struct {
	TotalFeedBack        int32         `protobuf:"varint,1,opt,name=totalFeedBack,proto3" json:"totalFeedBack,omitempty"`
	ResponseStatus       *ResponseInfo `protobuf:"bytes,2,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteFeedBackResponse) Reset()         { *m = DeleteFeedBackResponse{} }
func (m *DeleteFeedBackResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFeedBackResponse) ProtoMessage()    {}
func (*DeleteFeedBackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_98d0088042d0906b, []int{21}
}
func (m *DeleteFeedBackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeedBackResponse.Unmarshal(m, b)
}
func (m *DeleteFeedBackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeedBackResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFeedBackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeedBackResponse.Merge(dst, src)
}
func (m *DeleteFeedBackResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFeedBackResponse.Size(m)
}
func (m *DeleteFeedBackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeedBackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeedBackResponse proto.InternalMessageInfo

func (m *DeleteFeedBackResponse) GetTotalFeedBack() int32 {
	if m != nil {
		return m.TotalFeedBack
	}
	return 0
}

func (m *DeleteFeedBackResponse) GetResponseStatus() *ResponseInfo {
	if m != nil {
		return m.ResponseStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseInfo)(nil), "customerfeedback.ResponseInfo")
	proto.RegisterType((*PagingRequest)(nil), "customerfeedback.PagingRequest")
	proto.RegisterType((*PagingResponse)(nil), "customerfeedback.PagingResponse")
	proto.RegisterType((*CreatePassengerRequest)(nil), "customerfeedback.CreatePassengerRequest")
	proto.RegisterType((*PassengerInfoResponse)(nil), "customerfeedback.PassengerInfoResponse")
	proto.RegisterType((*GetPassengerRequest)(nil), "customerfeedback.GetPassengerRequest")
	proto.RegisterType((*Location)(nil), "customerfeedback.Location")
	proto.RegisterType((*CreateBookingRequest)(nil), "customerfeedback.CreateBookingRequest")
	proto.RegisterType((*BookingInfoResponse)(nil), "customerfeedback.BookingInfoResponse")
	proto.RegisterType((*CreateBookingResponse)(nil), "customerfeedback.CreateBookingResponse")
	proto.RegisterType((*GetBookingRequest)(nil), "customerfeedback.GetBookingRequest")
	proto.RegisterType((*GetBookingRequestByPassengerId)(nil), "customerfeedback.GetBookingRequestByPassengerId")
	proto.RegisterType((*PassengerBookingResponse)(nil), "customerfeedback.PassengerBookingResponse")
	proto.RegisterType((*CreateFeedbackRequest)(nil), "customerfeedback.CreateFeedbackRequest")
	proto.RegisterType((*CreateFeedbackResponse)(nil), "customerfeedback.CreateFeedbackResponse")
	proto.RegisterType((*FeedbackInfoResponse)(nil), "customerfeedback.FeedbackInfoResponse")
	proto.RegisterType((*GetFeedbackResponse)(nil), "customerfeedback.GetFeedbackResponse")
	proto.RegisterType((*GetFeedbackByBookingCode)(nil), "customerfeedback.GetFeedbackByBookingCode")
	proto.RegisterType((*GetFeedbackByPassengerId)(nil), "customerfeedback.GetFeedbackByPassengerId")
	proto.RegisterType((*PassengerFeedbackResponse)(nil), "customerfeedback.PassengerFeedbackResponse")
	proto.RegisterType((*DeleteFeedbackByPassengerId)(nil), "customerfeedback.DeleteFeedbackByPassengerId")
	proto.RegisterType((*DeleteFeedBackResponse)(nil), "customerfeedback.DeleteFeedBackResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PassengerFeedbackServiceClient is the client API for PassengerFeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerFeedbackServiceClient interface {
	// passenger
	AddNewPassenger(ctx context.Context, in *CreatePassengerRequest, opts ...grpc.CallOption) (*PassengerInfoResponse, error)
	GetPassengerById(ctx context.Context, in *GetPassengerRequest, opts ...grpc.CallOption) (*PassengerInfoResponse, error)
	// booking
	AddBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error)
	GetBookingByCode(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*BookingInfoResponse, error)
	GetBookingByPassengerId(ctx context.Context, in *GetBookingRequestByPassengerId, opts ...grpc.CallOption) (*PassengerBookingResponse, error)
	// feedback
	// + Add passenger feedback
	CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*CreateFeedbackResponse, error)
	// + Get by booking code
	GetFeedbackByBookingCode(ctx context.Context, in *GetFeedbackByBookingCode, opts ...grpc.CallOption) (*GetFeedbackResponse, error)
	// + Get by passenger id
	GetFeedbackByPassengerId(ctx context.Context, in *GetFeedbackByPassengerId, opts ...grpc.CallOption) (*PassengerFeedbackResponse, error)
	// + Delete by passenger id
	DeleteFeedbackByPassengerId(ctx context.Context, in *DeleteFeedbackByPassengerId, opts ...grpc.CallOption) (*DeleteFeedBackResponse, error)
}

type passengerFeedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewPassengerFeedbackServiceClient(cc *grpc.ClientConn) PassengerFeedbackServiceClient {
	return &passengerFeedbackServiceClient{cc}
}

func (c *passengerFeedbackServiceClient) AddNewPassenger(ctx context.Context, in *CreatePassengerRequest, opts ...grpc.CallOption) (*PassengerInfoResponse, error) {
	out := new(PassengerInfoResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/addNewPassenger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetPassengerById(ctx context.Context, in *GetPassengerRequest, opts ...grpc.CallOption) (*PassengerInfoResponse, error) {
	out := new(PassengerInfoResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/getPassengerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) AddBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error) {
	out := new(CreateBookingResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/addBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetBookingByCode(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*BookingInfoResponse, error) {
	out := new(BookingInfoResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/getBookingByCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetBookingByPassengerId(ctx context.Context, in *GetBookingRequestByPassengerId, opts ...grpc.CallOption) (*PassengerBookingResponse, error) {
	out := new(PassengerBookingResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/getBookingByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*CreateFeedbackResponse, error) {
	out := new(CreateFeedbackResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/createFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetFeedbackByBookingCode(ctx context.Context, in *GetFeedbackByBookingCode, opts ...grpc.CallOption) (*GetFeedbackResponse, error) {
	out := new(GetFeedbackResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/getFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetFeedbackByPassengerId(ctx context.Context, in *GetFeedbackByPassengerId, opts ...grpc.CallOption) (*PassengerFeedbackResponse, error) {
	out := new(PassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/getFeedbackByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) DeleteFeedbackByPassengerId(ctx context.Context, in *DeleteFeedbackByPassengerId, opts ...grpc.CallOption) (*DeleteFeedBackResponse, error) {
	out := new(DeleteFeedBackResponse)
	err := c.cc.Invoke(ctx, "/customerfeedback.PassengerFeedbackService/deleteFeedbackByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerFeedbackServiceServer is the server API for PassengerFeedbackService service.
type PassengerFeedbackServiceServer interface {
	// passenger
	AddNewPassenger(context.Context, *CreatePassengerRequest) (*PassengerInfoResponse, error)
	GetPassengerById(context.Context, *GetPassengerRequest) (*PassengerInfoResponse, error)
	// booking
	AddBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error)
	GetBookingByCode(context.Context, *GetBookingRequest) (*BookingInfoResponse, error)
	GetBookingByPassengerId(context.Context, *GetBookingRequestByPassengerId) (*PassengerBookingResponse, error)
	// feedback
	// + Add passenger feedback
	CreateFeedback(context.Context, *CreateFeedbackRequest) (*CreateFeedbackResponse, error)
	// + Get by booking code
	GetFeedbackByBookingCode(context.Context, *GetFeedbackByBookingCode) (*GetFeedbackResponse, error)
	// + Get by passenger id
	GetFeedbackByPassengerId(context.Context, *GetFeedbackByPassengerId) (*PassengerFeedbackResponse, error)
	// + Delete by passenger id
	DeleteFeedbackByPassengerId(context.Context, *DeleteFeedbackByPassengerId) (*DeleteFeedBackResponse, error)
}

func RegisterPassengerFeedbackServiceServer(s *grpc.Server, srv PassengerFeedbackServiceServer) {
	s.RegisterService(&_PassengerFeedbackService_serviceDesc, srv)
}

func _PassengerFeedbackService_AddNewPassenger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).AddNewPassenger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/AddNewPassenger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).AddNewPassenger(ctx, req.(*CreatePassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetPassengerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetPassengerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/GetPassengerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetPassengerById(ctx, req.(*GetPassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_AddBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).AddBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/AddBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).AddBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetBookingByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetBookingByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/GetBookingByCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetBookingByCode(ctx, req.(*GetBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetBookingByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingRequestByPassengerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetBookingByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/GetBookingByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetBookingByPassengerId(ctx, req.(*GetBookingRequestByPassengerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_CreateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).CreateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/CreateFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).CreateFeedback(ctx, req.(*CreateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackByBookingCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/GetFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetFeedbackByBookingCode(ctx, req.(*GetFeedbackByBookingCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetFeedbackByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackByPassengerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetFeedbackByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/GetFeedbackByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetFeedbackByPassengerId(ctx, req.(*GetFeedbackByPassengerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_DeleteFeedbackByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedbackByPassengerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).DeleteFeedbackByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customerfeedback.PassengerFeedbackService/DeleteFeedbackByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).DeleteFeedbackByPassengerId(ctx, req.(*DeleteFeedbackByPassengerId))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassengerFeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customerfeedback.PassengerFeedbackService",
	HandlerType: (*PassengerFeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addNewPassenger",
			Handler:    _PassengerFeedbackService_AddNewPassenger_Handler,
		},
		{
			MethodName: "getPassengerById",
			Handler:    _PassengerFeedbackService_GetPassengerById_Handler,
		},
		{
			MethodName: "addBooking",
			Handler:    _PassengerFeedbackService_AddBooking_Handler,
		},
		{
			MethodName: "getBookingByCode",
			Handler:    _PassengerFeedbackService_GetBookingByCode_Handler,
		},
		{
			MethodName: "getBookingByPassengerId",
			Handler:    _PassengerFeedbackService_GetBookingByPassengerId_Handler,
		},
		{
			MethodName: "createFeedback",
			Handler:    _PassengerFeedbackService_CreateFeedback_Handler,
		},
		{
			MethodName: "getFeedbackByBookingCode",
			Handler:    _PassengerFeedbackService_GetFeedbackByBookingCode_Handler,
		},
		{
			MethodName: "getFeedbackByPassengerId",
			Handler:    _PassengerFeedbackService_GetFeedbackByPassengerId_Handler,
		},
		{
			MethodName: "deleteFeedbackByPassengerId",
			Handler:    _PassengerFeedbackService_DeleteFeedbackByPassengerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_services_98d0088042d0906b) }

var fileDescriptor_services_98d0088042d0906b = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0x5f, 0x67, 0x13, 0xe2, 0xbc, 0x6c, 0xb3, 0x61, 0x16, 0x16, 0x93, 0x45, 0xdd, 0x6a, 0xa0,
	0x25, 0x2a, 0x90, 0x45, 0x41, 0x20, 0x0e, 0x2b, 0xad, 0xd6, 0x5b, 0xc2, 0x77, 0x15, 0xb9, 0xdc,
	0xa9, 0x63, 0x4f, 0x8c, 0xd5, 0x26, 0x13, 0x6c, 0x07, 0x1a, 0xae, 0x48, 0x48, 0xdc, 0xb9, 0xc1,
	0x81, 0xfe, 0x85, 0x3d, 0xf0, 0x0f, 0x30, 0x99, 0xcc, 0x38, 0x63, 0x7b, 0xf2, 0xd1, 0xaa, 0x88,
	0xbd, 0x58, 0x33, 0xcf, 0xef, 0xeb, 0xf7, 0x9b, 0xf7, 0xde, 0x0c, 0x34, 0x62, 0x12, 0xfd, 0x14,
	0x7a, 0x24, 0xee, 0x4c, 0x22, 0x9a, 0x50, 0xd4, 0xf4, 0xa6, 0x71, 0x42, 0x47, 0x24, 0x1a, 0x12,
	0xe2, 0x0f, 0x5c, 0xef, 0xac, 0xf5, 0x38, 0xa0, 0x34, 0x38, 0x27, 0x4f, 0xf8, 0xff, 0xc1, 0x74,
	0xf8, 0x24, 0x09, 0x47, 0x24, 0x4e, 0xdc, 0xd1, 0x64, 0x61, 0x82, 0x9f, 0xc2, 0x3d, 0x87, 0xc4,
	0x13, 0x3a, 0x8e, 0xc9, 0x97, 0xe3, 0x21, 0x45, 0x16, 0x54, 0x99, 0x42, 0xec, 0x06, 0xc4, 0x32,
	0xf6, 0x8c, 0x76, 0xcd, 0x91, 0x5b, 0x84, 0xa0, 0xec, 0x51, 0x9f, 0x58, 0x25, 0x26, 0xae, 0x38,
	0x7c, 0x8d, 0xbf, 0x86, 0x9d, 0xbe, 0x1b, 0x84, 0xe3, 0xc0, 0x21, 0x3f, 0x4e, 0x99, 0x5f, 0xb4,
	0x0b, 0x30, 0x61, 0xca, 0xc7, 0xd3, 0xd1, 0x80, 0x44, 0xdc, 0x43, 0xc5, 0x51, 0x24, 0xa8, 0x05,
	0xe6, 0x7c, 0x77, 0x12, 0xfe, 0x22, 0x1d, 0xa5, 0x7b, 0xdc, 0x87, 0x86, 0x74, 0xb6, 0x48, 0x08,
	0xbd, 0x05, 0xb5, 0x84, 0x26, 0xee, 0x79, 0x5f, 0xa6, 0x53, 0x71, 0x96, 0x02, 0xb4, 0x07, 0x75,
	0xbe, 0x71, 0x88, 0x47, 0x23, 0x5f, 0xb8, 0x53, 0x45, 0xf8, 0x7d, 0x78, 0xf8, 0x22, 0x22, 0x6e,
	0x42, 0xfa, 0x6e, 0x1c, 0x93, 0x71, 0x40, 0x22, 0x99, 0x27, 0x03, 0x33, 0x76, 0x47, 0x12, 0x23,
	0x5f, 0xe3, 0x3f, 0x0d, 0x78, 0x3d, 0x55, 0x9c, 0x93, 0x91, 0xe6, 0xd1, 0x80, 0x52, 0xe8, 0x0b,
	0x5d, 0xb6, 0x4a, 0xad, 0x4b, 0x4b, 0x6b, 0xd4, 0x83, 0x46, 0x24, 0xf4, 0x4f, 0x12, 0x37, 0x99,
	0xc6, 0xd6, 0x5d, 0xf6, 0xb7, 0xde, 0xdd, 0xed, 0xe4, 0x0f, 0xa5, 0xa3, 0x12, 0xee, 0xe4, 0xac,
	0xbe, 0x2a, 0x9b, 0xd5, 0xa6, 0xc9, 0xbe, 0x66, 0xb3, 0xc6, 0xbe, 0xb5, 0x26, 0xb0, 0x2f, 0x34,
	0xeb, 0x78, 0x1f, 0x1e, 0x7c, 0x4e, 0x92, 0x02, 0x90, 0x5c, 0x6a, 0xf8, 0x00, 0xcc, 0x6f, 0xa8,
	0xe7, 0x26, 0x21, 0x1d, 0xa3, 0x7b, 0x60, 0x5c, 0x08, 0xda, 0x8c, 0x8b, 0xf9, 0x6e, 0x26, 0x48,
	0x32, 0x66, 0xf8, 0x0f, 0x03, 0x5e, 0x5b, 0x70, 0x63, 0x53, 0x7a, 0xa6, 0x9c, 0x20, 0x63, 0x75,
	0x92, 0x92, 0x20, 0x3d, 0xab, 0x22, 0xd4, 0x81, 0xf2, 0x30, 0xa2, 0x23, 0xee, 0xab, 0xde, 0x6d,
	0x15, 0xf1, 0xc9, 0x04, 0x1c, 0xae, 0x87, 0x0e, 0xa1, 0x94, 0x50, 0xc1, 0xc6, 0x3a, 0x6d, 0xa6,
	0x85, 0x2f, 0x4b, 0xf0, 0x40, 0x24, 0x94, 0x39, 0x01, 0x96, 0xd5, 0x60, 0x21, 0x7e, 0x31, 0xaf,
	0x41, 0x91, 0x95, 0x22, 0xfa, 0x2f, 0xb3, 0x9a, 0x57, 0x6d, 0x18, 0xf7, 0xc2, 0x71, 0x18, 0xff,
	0x60, 0x95, 0x99, 0x85, 0xe9, 0xa4, 0x7b, 0xf4, 0x29, 0xd4, 0x3c, 0xce, 0xa3, 0xff, 0x3c, 0xb1,
	0x4c, 0xe1, 0x6e, 0xd1, 0x75, 0x1d, 0xd9, 0x75, 0x9d, 0xef, 0x64, 0xd7, 0x39, 0x4b, 0x65, 0xf4,
	0x09, 0x98, 0x43, 0xee, 0x83, 0x19, 0xd6, 0x36, 0x1a, 0xa6, 0xba, 0xf8, 0x6f, 0x56, 0xa7, 0xb9,
	0xa3, 0x13, 0x2c, 0x3d, 0x83, 0xaa, 0xa0, 0x84, 0x33, 0x54, 0xef, 0xee, 0x17, 0x81, 0x69, 0xd8,
	0x75, 0xa4, 0x95, 0xa6, 0x88, 0x4b, 0x37, 0x29, 0x62, 0xfc, 0x31, 0xbc, 0xca, 0x8a, 0xb5, 0x58,
	0x59, 0xeb, 0xcf, 0x10, 0xff, 0x6e, 0xc0, 0x6e, 0xc1, 0xce, 0x9e, 0xf5, 0x95, 0xe2, 0xdb, 0x5c,
	0x9e, 0x9f, 0xc1, 0xce, 0x44, 0x9d, 0x49, 0x02, 0xc2, 0xe3, 0x22, 0x84, 0xcc, 0xe8, 0x72, 0xb2,
	0x56, 0xf8, 0xca, 0x00, 0x2b, 0x0d, 0x9c, 0x27, 0xfa, 0x39, 0x98, 0x22, 0xef, 0x98, 0xa5, 0x70,
	0x77, 0x7b, 0xa6, 0x53, 0xb3, 0xdb, 0xa2, 0x1a, 0x7d, 0x01, 0x8d, 0x49, 0x66, 0x6a, 0x5a, 0x15,
	0xee, 0x67, 0x6f, 0x35, 0x5e, 0x91, 0x4b, 0xce, 0x0e, 0x7b, 0xb2, 0xac, 0x7a, 0xc2, 0x60, 0xeb,
	0x83, 0x43, 0x6d, 0xb8, 0x2f, 0xa3, 0x7c, 0x2b, 0x6e, 0x8f, 0xc5, 0x6c, 0xcc, 0x8b, 0xf1, 0xa9,
	0x1c, 0xc9, 0xcb, 0x20, 0x82, 0xd3, 0x22, 0x21, 0xc6, 0x8d, 0x6a, 0xef, 0x2f, 0x36, 0xd9, 0xa4,
	0xf3, 0x6b, 0xce, 0x90, 0xad, 0x61, 0xdc, 0xbc, 0xeb, 0xf1, 0xa5, 0xc1, 0x07, 0x79, 0x01, 0xbe,
	0xcd, 0xa6, 0x01, 0x93, 0xd9, 0x4c, 0x26, 0x80, 0x1f, 0x14, 0x81, 0xeb, 0x70, 0x39, 0xa9, 0xdd,
	0xad, 0xb5, 0xef, 0x53, 0xb0, 0x94, 0x14, 0xed, 0x99, 0xad, 0x70, 0xb4, 0xb9, 0x8b, 0x7f, 0x35,
	0x72, 0xe6, 0xff, 0x4b, 0xff, 0xfe, 0x63, 0xc0, 0x9b, 0x69, 0xe0, 0x02, 0xdb, 0x47, 0x50, 0x93,
	0x6e, 0x64, 0x07, 0x6f, 0x4b, 0xf7, 0xd2, 0xf0, 0x25, 0xec, 0xe1, 0x67, 0xf0, 0xe8, 0x88, 0x9c,
	0x93, 0x65, 0x7b, 0x5d, 0x93, 0x7d, 0xfc, 0x9b, 0x01, 0x0f, 0x97, 0x1e, 0x6c, 0x95, 0xb3, 0x77,
	0x60, 0x87, 0x3f, 0xae, 0x7a, 0x6a, 0x99, 0x56, 0x9c, 0xac, 0xf0, 0xb6, 0x38, 0xe9, 0x5e, 0x55,
	0x95, 0xf9, 0x2b, 0xd1, 0x9c, 0x2c, 0xde, 0xbb, 0x68, 0x08, 0xf7, 0x5d, 0xdf, 0x3f, 0x26, 0x3f,
	0xa7, 0x1a, 0xa8, 0x5d, 0xf4, 0xaf, 0x7f, 0xfb, 0xb5, 0xde, 0xd5, 0xb1, 0xaa, 0x79, 0xf6, 0xe1,
	0x3b, 0xc8, 0x87, 0x66, 0xa0, 0x3c, 0xba, 0xec, 0x19, 0xe3, 0x50, 0x33, 0xe9, 0x35, 0x0f, 0xb3,
	0xeb, 0x44, 0xf9, 0x1e, 0x80, 0xa1, 0x11, 0x4d, 0x86, 0x0e, 0x56, 0x01, 0xc9, 0x5e, 0x8b, 0xba,
	0x00, 0xda, 0x57, 0x01, 0x0b, 0x70, 0xca, 0x61, 0x08, 0xb9, 0x3d, 0xe3, 0x7d, 0xfc, 0xb6, 0x16,
	0x46, 0x2e, 0xc6, 0x76, 0xb7, 0x1a, 0x8b, 0x30, 0x83, 0x37, 0xd4, 0x08, 0x6a, 0xcd, 0x7d, 0xb8,
	0x45, 0xa0, 0x8c, 0x45, 0xeb, 0x70, 0x0d, 0x75, 0x45, 0x70, 0x04, 0x1a, 0x5e, 0xe6, 0x46, 0x41,
	0x2b, 0x99, 0xc9, 0x5d, 0x6c, 0xad, 0xf6, 0x66, 0xc5, 0x34, 0x0c, 0x05, 0x2b, 0x58, 0x35, 0x13,
	0x0f, 0xb5, 0x10, 0xb5, 0xba, 0xad, 0xfd, 0xb5, 0xba, 0x4a, 0xc0, 0x69, 0x2e, 0xa0, 0xca, 0xe9,
	0xa6, 0x80, 0x2a, 0x9b, 0xef, 0xad, 0x61, 0x53, 0x13, 0xf6, 0x02, 0x1e, 0xf9, 0x6b, 0x26, 0xc8,
	0x07, 0x45, 0x6f, 0x6b, 0x06, 0x8e, 0x8e, 0x61, 0xfd, 0x74, 0xc1, 0x77, 0x06, 0xaf, 0xf0, 0x8b,
	0xf3, 0xa3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x34, 0xea, 0x78, 0xd6, 0x0e, 0x00, 0x00,
}
